//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Ocr.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Ocr.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a bank card..
        /// </summary>
        public static string BankCardActivity_Description {
            get {
                return ResourceManager.GetString("BankCardActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Card.
        /// </summary>
        public static string BankCardActivity_DisplayName {
            get {
                return ResourceManager.GetString("BankCardActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path to the image for recognition..
        /// </summary>
        public static string BaseOcrActivity_ImagePath_Description {
            get {
                return ResourceManager.GetString("BaseOcrActivity_ImagePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagePath.
        /// </summary>
        public static string BaseOcrActivity_ImagePath_DisplayName {
            get {
                return ResourceManager.GetString("BaseOcrActivity_ImagePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the recognition in the form of JSON..
        /// </summary>
        public static string BaseOcrActivity_Result_Description {
            get {
                return ResourceManager.GetString("BaseOcrActivity_Result_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string BaseOcrActivity_Result_DisplayName {
            get {
                return ResourceManager.GetString("BaseOcrActivity_Result_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a birth certificate..
        /// </summary>
        public static string BirthCertificateActivity_Description {
            get {
                return ResourceManager.GetString("BirthCertificateActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Certificate.
        /// </summary>
        public static string BirthCertificateActivity_DisplayName {
            get {
                return ResourceManager.GetString("BirthCertificateActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a business license..
        /// </summary>
        public static string BusinessLicenseActivity_Description {
            get {
                return ResourceManager.GetString("BusinessLicenseActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business License.
        /// </summary>
        public static string BusinessLicenseActivity_DisplayName {
            get {
                return ResourceManager.GetString("BusinessLicenseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a driver license..
        /// </summary>
        public static string DriverLicenseActivity_Description {
            get {
                return ResourceManager.GetString("DriverLicenseActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver License.
        /// </summary>
        public static string DriverLicenseActivity_DisplayName {
            get {
                return ResourceManager.GetString("DriverLicenseActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a HK and Macau pass..
        /// </summary>
        public static string HkMacauExitentrypermitActivity_Description {
            get {
                return ResourceManager.GetString("HkMacauExitentrypermitActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK and Macau Pass.
        /// </summary>
        public static string HkMacauExitentrypermitActivity_DisplayName {
            get {
                return ResourceManager.GetString("HkMacauExitentrypermitActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a household register..
        /// </summary>
        public static string HouseholdRegisterActivity_Description {
            get {
                return ResourceManager.GetString("HouseholdRegisterActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Register.
        /// </summary>
        public static string HouseholdRegisterActivity_DisplayName {
            get {
                return ResourceManager.GetString("HouseholdRegisterActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate which side of the card to recognize..
        /// </summary>
        public static string IdCardActivity_CardSide_Description {
            get {
                return ResourceManager.GetString("IdCardActivity_CardSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardSide.
        /// </summary>
        public static string IdCardActivity_CardSide_DisplayName {
            get {
                return ResourceManager.GetString("IdCardActivity_CardSide_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a ID card..
        /// </summary>
        public static string IdCardActivity_Description {
            get {
                return ResourceManager.GetString("IdCardActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string IdCardActivity_DisplayName {
            get {
                return ResourceManager.GetString("IdCardActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON string to return as JObject. If you don&apos;t provide a value, a default JObject will be returned..
        /// </summary>
        public static string MockOcrClientActivity_Content_Description {
            get {
                return ResourceManager.GetString("MockOcrClientActivity_Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string MockOcrClientActivity_Content_DisplayName {
            get {
                return ResourceManager.GetString("MockOcrClientActivity_Content_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injects MockOcrClient as IOcrClient in ObjectContainer..
        /// </summary>
        public static string MockOcrClientActivity_Description {
            get {
                return ResourceManager.GetString("MockOcrClientActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock OCR Client.
        /// </summary>
        public static string MockOcrClientActivity_DisplayName {
            get {
                return ResourceManager.GetString("MockOcrClientActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains and authenticates all Ccint OCR activities..
        /// </summary>
        public static string OcrScope_Description {
            get {
                return ResourceManager.GetString("OcrScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR Scope.
        /// </summary>
        public static string OcrScope_DisplayName {
            get {
                return ResourceManager.GetString("OcrScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a passport..
        /// </summary>
        public static string PassportActivity_Description {
            get {
                return ResourceManager.GetString("PassportActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string PassportActivity_DisplayName {
            get {
                return ResourceManager.GetString("PassportActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a quota invoice..
        /// </summary>
        public static string QuotaInvoiceActivity_Description {
            get {
                return ResourceManager.GetString("QuotaInvoiceActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Invoice.
        /// </summary>
        public static string QuotaInvoiceActivity_DisplayName {
            get {
                return ResourceManager.GetString("QuotaInvoiceActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a Taiwan pass..
        /// </summary>
        public static string TaiwanExitentrypermitActivity_Description {
            get {
                return ResourceManager.GetString("TaiwanExitentrypermitActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan Pass.
        /// </summary>
        public static string TaiwanExitentrypermitActivity_DisplayName {
            get {
                return ResourceManager.GetString("TaiwanExitentrypermitActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a taxi receipt..
        /// </summary>
        public static string TaxiReceiptActivity_Description {
            get {
                return ResourceManager.GetString("TaxiReceiptActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Receipt.
        /// </summary>
        public static string TaxiReceiptActivity_DisplayName {
            get {
                return ResourceManager.GetString("TaxiReceiptActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a train ticket..
        /// </summary>
        public static string TrainTicketActivity_Description {
            get {
                return ResourceManager.GetString("TrainTicketActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Ticket.
        /// </summary>
        public static string TrainTicketActivity_DisplayName {
            get {
                return ResourceManager.GetString("TrainTicketActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a VAT invoice..
        /// </summary>
        public static string VatInvoiceActivity_Description {
            get {
                return ResourceManager.GetString("VatInvoiceActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Invoice.
        /// </summary>
        public static string VatInvoiceActivity_DisplayName {
            get {
                return ResourceManager.GetString("VatInvoiceActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a vehicle certificate..
        /// </summary>
        public static string VehicleCertificateActivity_Description {
            get {
                return ResourceManager.GetString("VehicleCertificateActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Certificate.
        /// </summary>
        public static string VehicleCertificateActivity_DisplayName {
            get {
                return ResourceManager.GetString("VehicleCertificateActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a vehicle invoice..
        /// </summary>
        public static string VehicleInvoiceActivity_Description {
            get {
                return ResourceManager.GetString("VehicleInvoiceActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Invoice.
        /// </summary>
        public static string VehicleInvoiceActivity_DisplayName {
            get {
                return ResourceManager.GetString("VehicleInvoiceActivity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a vehicle license..
        /// </summary>
        public static string VehicleLicenseActivity_Description {
            get {
                return ResourceManager.GetString("VehicleLicenseActivity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle License.
        /// </summary>
        public static string VehicleLicenseActivity_DisplayName {
            get {
                return ResourceManager.GetString("VehicleLicenseActivity_DisplayName", resourceCulture);
            }
        }
    }
}
